project:
  type: website
  output-dir: docs

website:
  title: "SFC1018"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left
    toc-depth: 4
    toc-expand: 2
    number-sections: true
    number-depth: 4


