project:
  type: website
  output-dir: docs

website:
  title: "SFC1018"
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - about.qmd
  sidebar:
    style: "docked"
    search: true
    # contents: auto
    contents:
      - section: "Les bases"
        contents:
          - SFC1018_Intro_R.qmd
      - section: "Traitement de données"
        contents:
          - SFC1018_Traitement_R.qmd
      - section: "Manipulation de données"
        contents:
          - SFC1018_Manipulation_R.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4
    toc-expand: 2
    number-sections: true
    number-depth: 4


